name: Ticket Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: echo "workflow works"
